# Regenerated by Claude Code edited by George Chacko
# Ablation dumbbell plot: P5 vs PS5 across 8 ablation conditions
# Files located on IL campus cluster storage

rm(list = ls())
library(data.table)
library(ggplot2)
library(patchwork)

# ── Paths & thresholds ────────────────────────────────────────────────────────
root_dir <- "/projects/illinois/eng/cs/chackoge/illinoiscomputes/abm/v6/chacko/ablation"
out_dir  <- root_dir

BSL_THRESH_999  <- 1707
BSL_THRESH_9999 <- 9018

# ── Condition → directory stem mapping ───────────────────────────────────────
# Note: naw has an extra underscore in the directory name
cond_map <- list(
  "A0: Reference"       = list(p5 = "p5ablation_fullref",  ps5 = "ps5ablation_fullref"),
  "A1: Remove PA wt."   = list(p5 = "p5ablation_pa",       ps5 = "ps5ablation_pa"),
  "A2: Remove fit. wt." = list(p5 = "p5ablation_fitw",     ps5 = "ps5ablation_fitw"),
  "A3: Remove NA wt."   = list(p5 = "p5_ablation_naw",     ps5 = "ps5_ablation_naw"),
  "A4: Remove AR wt."   = list(p5 = "p5ablation_arw",      ps5 = "ps5ablation_arw"),
  "A5: Ablate fitness"  = list(p5 = "p5ablation_fitness",  ps5 = "ps5ablation_fitness"),
  "A6: Ablate NA"       = list(p5 = "p5ablation_na_val",   ps5 = "ps5ablation_na_val"),
  "A7: Ablate OD"       = list(p5 = "p5ablation_od_val",   ps5 = "ps5ablation_od_val")
)

# ── Compute stats for one series/condition ────────────────────────────────────
get_stats <- function(series_dir, stem) {
  dirs <- paste0(stem, "_r", 0:2)
  pool <- rbindlist(lapply(dirs, function(d) {
    f  <- file.path(series_dir, d, "output", "nodelist.csv")
    dt <- fread(f, select = c("planted_nodes_line_number", "in_degree"))
    dt[planted_nodes_line_number != -1, .(in_degree)]
  }))
  x <- pool$in_degree
  list(median = median(x),
       pct_999  = 100 * mean(x >= BSL_THRESH_999),
       pct_9999 = 100 * mean(x >= BSL_THRESH_9999))
}

# ── Build results table ───────────────────────────────────────────────────────
p5_dir  <- file.path(root_dir, "p5_ablation")
ps5_dir <- file.path(root_dir, "ps5_ablation")

results <- rbindlist(lapply(names(cond_map), function(cond) {
  cat("Processing", cond, "\n")
  p5  <- get_stats(p5_dir,  cond_map[[cond]]$p5)
  ps5 <- get_stats(ps5_dir, cond_map[[cond]]$ps5)
  data.table(
    cond        = cond,
    p5_median   = p5$median,   ps5_median   = ps5$median,
    p5_pct_999  = p5$pct_999,  ps5_pct_999  = ps5$pct_999,
    p5_pct_9999 = p5$pct_9999, ps5_pct_9999 = ps5$pct_9999
  )
}))

print(results)
write.csv(results, file.path(out_dir, "ablation_figure.csv"), row.names = FALSE)

# ── Factor order: A0 at bottom, A7 at top ────────────────────────────────────
cond_order <- names(cond_map)
results[, cond := factor(cond, levels = cond_order)]

# ── Colours ───────────────────────────────────────────────────────────────────
COL_P5   <- "#2166ac"
COL_PS5  <- "#d6604d"
COL_LINE <- "#aaaaaa"
FONT     <- 16

palette  <- c("P5 (simultaneous)" = COL_P5, "PS5 (staggered)" = COL_PS5)

# ── Dumbbell helper ───────────────────────────────────────────────────────────
make_dumbbell <- function(dt, p5_col, ps5_col, xlabel, xlim = NULL, pct_line = FALSE,
                          show_y = TRUE, show_legend = FALSE) {
  long <- rbind(
    dt[, .(cond, x = get(p5_col),  series = "P5 (simultaneous)")],
    dt[, .(cond, x = get(ps5_col), series = "PS5 (staggered)")]
  )
  long[, series := factor(series, levels = c("P5 (simultaneous)", "PS5 (staggered)"))]

  p <- ggplot() +
    geom_segment(data = dt,
                 aes(x = get(p5_col), xend = get(ps5_col), y = cond, yend = cond),
                 colour = COL_LINE, linewidth = 1.2) +
    geom_point(data = long, aes(x = x, y = cond, colour = series), size = 3) +
    scale_colour_manual(values = palette, name = NULL) +
    labs(x = xlabel, y = NULL) +
    theme_bw(base_size = FONT) +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.minor   = element_blank(),
      panel.grid.major.x = element_line(linetype = "dotted", linewidth = 0.7, colour = "grey70"),
      axis.text.x        = element_text(size = FONT - 2),
      axis.title.x       = element_text(size = FONT),
      legend.position    = "none",
      panel.border       = element_rect(colour = "grey80")
    )

  if (show_y) {
    p <- p + theme(axis.text.y = element_text(size = FONT - 2))
  } else {
    p <- p + theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
  }

  if (!is.null(xlim)) p <- p + scale_x_continuous(limits = xlim)
  if (pct_line)       p <- p + geom_vline(xintercept = 100, linetype = "dashed",
                                           colour = "#cccccc", linewidth = 0.8)
  if (show_legend) {
    p <- p +
      guides(colour = guide_legend(override.aes = list(size = 4))) +
      theme(legend.position   = c(0.3, 0.12),
            legend.background = element_blank(),
            legend.text       = element_text(size = FONT - 2))
  }
  p
}

# ── Build panels ──────────────────────────────────────────────────────────────
p1 <- make_dumbbell(results, "p5_median", "ps5_median", "Median in-degree",
                    show_y = TRUE) +
  scale_x_continuous(labels = function(x)
    ifelse(x >= 1000, paste0(x / 1000, "k"), as.character(x)))

p2 <- make_dumbbell(results, "p5_pct_999", "ps5_pct_999",
                    "% Agents >= p99.9 bsl",
                    xlim = c(25, 110), pct_line = TRUE,
                    show_y = FALSE, show_legend = TRUE)

p3 <- make_dumbbell(results, "p5_pct_9999", "ps5_pct_9999",
                    "% Agents >= p99.99 bsl",
                    xlim = c(25, 110), pct_line = TRUE,
                    show_y = FALSE)

# ── Combine and save ──────────────────────────────────────────────────────────
combined <- p1 + p2 + p3 + plot_layout(widths = c(1.3, 1, 1))

ggsave(file.path(out_dir, "ablation_figure.pdf"), combined,
       width = 16, height = 6, units = "in", dpi = 300)
ggsave(file.path(out_dir, "ablation_figure.png"), combined,
       width = 16, height = 6, units = "in", dpi = 300)
ggsave(file.path(out_dir, "ablation_figure.eps"), combined,
       width = 16, height = 6, units = "in", dpi = 300, device = "eps")

cat("Saved ablation_figure.pdf/.png/.eps to", out_dir, "\n")
