# Regenerated by Claude Code. Edited and reviewed by George Chacko
# Heatmap: median agent attributes by in-degree tier, pooled across 10 baseline replicates

rm(list = ls())
library(data.table)
library(ggplot2)
library(RColorBrewer)

# ── Paths ─────────────────────────────────────────────────────────────────────
base_dir <- "/projects/illinois/eng/cs/chackoge/illinoiscomputes/abm/v6/chacko/claude_baseline_data"
out_dir  <- base_dir

baseline_files <- file.path(base_dir, paste0("bsl", 1:10), "output", "nodelist.csv")

cols_needed <- c("type", "in_degree", "year", "fit_peak_value", "out_degree",
                 "num_authors", "initial_author_reputation", "alpha")

# ── Pool all replicates ───────────────────────────────────────────────────────
cat("Reading and pooling replicates...\n")
pool <- rbindlist(lapply(seq_along(baseline_files), function(i) {
  cat("  bsl", i, "\n")
  dt <- fread(baseline_files[i], select = cols_needed)
  dt[type == "agent"]
}))
pool[, type := NULL]
cat("Total agents pooled:", nrow(pool), "\n")

# ── Tier thresholds (on pooled in_degree) ─────────────────────────────────────
q99   <- quantile(pool$in_degree, 0.99)
q999  <- quantile(pool$in_degree, 0.999)
q9999 <- quantile(pool$in_degree, 0.9999)

cat(sprintf("Tier cutoffs — Top 1%%: %g, Top 0.1%%: %g, Top 0.01%%: %g\n",
            q99, q999, q9999))

tiers <- list(
  "All agents" = pool,
  "Top 1%"     = pool[in_degree >= q99],
  "Top 0.1%"   = pool[in_degree >= q999],
  "Top 0.01%"  = pool[in_degree >= q9999]
)

vars <- c("year", "fit_peak_value", "out_degree", "num_authors",
          "initial_author_reputation", "alpha")

var_labels <- c(
  year                      = "Publication\nyear",
  fit_peak_value            = "Fitness",
  out_degree                = "Out-degree",
  num_authors               = "Number of\nauthors",
  initial_author_reputation = "Initial author\nreputation",
  alpha                     = "Alpha"
)

# ── Compute medians by tier and variable ──────────────────────────────────────
med_list <- lapply(names(tiers), function(tier_name) {
  dt <- tiers[[tier_name]]
  data.table(
    tier     = tier_name,
    variable = vars,
    median   = sapply(vars, function(v) median(dt[[v]]))
  )
})
med_dt <- rbindlist(med_list)

# ── Row-normalise (per variable, across tiers) ────────────────────────────────
med_dt[, norm := {
  mn <- min(median); mx <- max(median)
  if (mx == mn) rep(0.5, .N) else (median - mn) / (mx - mn)
}, by = variable]

# ── Format display labels ─────────────────────────────────────────────────────
med_dt[, display := ifelse(variable == "alpha",
                           sprintf("%.3f", median),
                           as.character(round(median)))]

# ── Factor ordering ───────────────────────────────────────────────────────────
tier_order <- c("All agents", "Top 1%", "Top 0.1%", "Top 0.01%")
var_order  <- rev(vars)   # top of plot = first var (year)

med_dt[, tier     := factor(tier, levels = tier_order)]
med_dt[, variable := factor(variable, levels = var_order,
                             labels = var_labels[var_order])]
med_dt[, text_col := ifelse(norm > 0.45, "white", "black")]

# ── Plot ──────────────────────────────────────────────────────────────────────
FONT_SIZE <- 16

pal <- colorRampPalette(c("#FFFDE7", "#FFCA28", "#EF5350", "#7B0000"))(100)

p <- ggplot(med_dt, aes(x = tier, y = variable, fill = norm)) +
  geom_tile(colour = "white", linewidth = 0.8) +
  geom_text(aes(label = display, colour = text_col),
            size = FONT_SIZE / .pt, fontface = "bold") +
  scale_fill_gradientn(colours = pal, limits = c(0, 1), guide = "none") +
  scale_colour_identity() +
  scale_x_discrete(position = "bottom") +
  labs(x = NULL, y = NULL) +
  theme_minimal(base_size = FONT_SIZE) +
  theme(
    axis.text.x      = element_text(size = FONT_SIZE, colour = "black"),
    axis.text.y      = element_text(size = FONT_SIZE, colour = "black", hjust = 1),
    panel.grid       = element_blank(),
    plot.background  = element_rect(fill = "white", colour = NA)
  )

# ── Save ──────────────────────────────────────────────────────────────────────
ggsave(file.path(out_dir, "baseline_heatmap.pdf"), plot = p,
       width = 8, height = 6, units = "in", dpi = 300)
ggsave(file.path(out_dir, "baseline_heatmap.png"), plot = p,
       width = 8, height = 6, units = "in", dpi = 300)
ggsave(file.path(out_dir, "baseline_heatmap.eps"), plot = p,
       width = 8, height = 6, units = "in", dpi = 300, device = "eps")

cat("Saved baseline_heatmap.pdf/.png/.eps to", out_dir, "\n")
print(med_dt[, .(tier, variable, median, norm, display)])
