# Regenerated by Claude Code. Reviewed by George Chacko
# OFAT table: in-degree distributional statistics across 11 conditions
# Stats pooled across 3 replicates per condition

rm(list = ls())
library(data.table)
library(xtable)

# ── Paths ─────────────────────────────────────────────────────────────────────
ofat_dir <- "/projects/illinois/eng/cs/chackoge/illinoiscomputes/abm/v6/chacko/ofats"
out_dir  <- ofat_dir

# Baseline thresholds (baseline 99.9th and 99.99th percentiles)
BSL_THRESH_999  <- 1707
BSL_THRESH_9999 <- 9018

# ── Condition → replicate directory mapping ───────────────────────────────────
conditions <- list(
  BSL_rand = c("ofat_bsl_random",    "ofat_bsl_randomr1",    "ofat_bsl_randomr2"),
  BSL_stat = c("ofat_bsl_static",    "ofat_bsl_staticr1",    "ofat_bsl_staticr2"),
  W1       = c("ofat_pa",            "ofat_par1",             "ofat_par2"),
  W2       = c("ofat_fit",           "ofat_fitr1",            "ofat_fitr2"),
  W3       = c("ofat_num_authors",   "ofat_num_authorsr1",    "ofat_num_authorsr2"),
  W4       = c("ofat_author_rep",    "ofat_author_repr1",     "ofat_author_repr2"),
  W5a      = c("ofat_w5astatic_hiod_r0", "ofat_w5astatic_hiod_r1", "ofat_w5astatic_hiod_r2"),
  W5b      = c("ofat_w5brand_hiod_r0",   "ofat_w5brand_hiod_r1",   "ofat_w5brand_hiod_r2"),
  W6a      = c("ofat_w5astatic_hialpha_r0", "ofat_w5astatic_hialpha_r1", "ofat_w5astatic_hialpha_r2"),
  W6b      = c("ofat_w5brand_hialpha_r0",   "ofat_w5brand_hialpha_r1",   "ofat_w5brand_hialpha_r2")
)

# ── Compute stats per condition ───────────────────────────────────────────────
results <- rbindlist(lapply(names(conditions), function(cond) {
  dirs <- conditions[[cond]]
  cat("Processing", cond, "\n")

  pool <- rbindlist(lapply(dirs, function(d) {
    f  <- file.path(ofat_dir, d, "output", "nodelist.csv")
    dt <- fread(f, select = c("type", "in_degree"))
    dt[type == "agent", .(in_degree)]
  }))

  x <- pool$in_degree
  n <- length(x)

  data.table(
    cond   = cond,
    median = median(x),
    mean   = mean(x),
    p999   = quantile(x, 0.999),
    p9999  = quantile(x, 0.9999),
    max    = max(x),
    pct_999  = 100 * mean(x >= BSL_THRESH_999),
    pct_9999 = 100 * mean(x >= BSL_THRESH_9999)
  )
}))

print(results)

# ── Build display table ───────────────────────────────────────────────────────
id_map <- c(
  BSL_rand = "",    BSL_stat = "",
  W1 = "W1", W2 = "W2", W3 = "W3", W4 = "W4",
  W5a = "W5a", W5b = "W5b",
  W6a = "W6a", W6b = "W6b"
)

label_map <- c(
  BSL_rand = "BSL\\_rand",
  BSL_stat = "BSL\\_stat",
  W1  = "pa\\_wt dominant",
  W2  = "fit\\_w dominant",
  W3  = "na\\_w dominant",
  W4  = "ar\\_w dominant",
  W5a = "Equal weights (0.25)",
  W5b = "randomised weights",
  W6a = "Equal weights (0.25)",
  W6b = "randomised weights"
)

disp <- results[, .(
  ID        = id_map[cond],
  Condition = label_map[cond],
  Median    = as.integer(round(median)),
  Mean      = round(mean, 1),
  p99.9     = formatC(round(p999),  format = "d", big.mark = ","),
  p99.99    = formatC(round(p9999), format = "d", big.mark = ","),
  Max       = formatC(max,          format = "d", big.mark = ","),
  pct_999   = sprintf("%.2f", pct_999),
  pct_9999  = sprintf("%.3f", pct_9999)
)]

# ── Save CSV ──────────────────────────────────────────────────────────────────
write.csv(results, file.path(out_dir, "ofat_indegree_table.csv"), row.names = FALSE)

# ── Build LaTeX manually (section headers + booktabs) ────────────────────────
tex_rows <- function(dt) {
  apply(dt, 1, function(r) {
    paste0("    ", paste(r, collapse = " & "), " \\\\")
  })
}

bsl_rows   <- tex_rows(disp[ID == ""])
w14_rows   <- tex_rows(disp[ID %in% c("W1","W2","W3","W4")])
w5_rows    <- tex_rows(disp[ID %in% c("W5a","W5b")])
w6_rows    <- tex_rows(disp[ID %in% c("W6a","W6b")])

latex <- c(
  "\\begin{table}[ht]",
  "\\centering",
  paste0("\\caption{OFAT experiment: in-degree distributional statistics across 11 conditions ",
         "(701,570 agents per replicate, 3 replicates per condition, with statistics pooled across replicates). ",
         "BSL\\_rand and BSL\\_stat are baseline conditions with phenotype weights either randomised or set to 0.25 respectively. ",
         "W1--W4 are weight conditions in which one citation weight is set to 0.91 and the remaining three to 0.03. ",
         " W5a and W5b fix out\\_degree at 249 for all agents with equal or randomised weights respectively; ",
         "W6a and W6b fix $\\alpha$ at 0.95 with either equal or randomised weights. ",
         "The top 0.1\\% and top 0.01\\% thresholds are defined relative to the baseline in-degree distribution ",
         "($\\geq$1,707 and $\\geq$9,018 citations respectively).}"),
  "\\label{tab:ofat_indegree}",
  "\\begin{tabular}{llrrrrrcc}",
  "\\toprule",
  "ID & Condition & Median & Mean & p99.9 & p99.99 & Max & \\% Agents $\\geq$ p99.9$_{\\text{bsl}}$ & Agents $\\geq$ p99.99$_{\\text{bsl}}$ \\\\",
  "\\midrule",
  "\\multicolumn{9}{l}{\\textit{Baseline conditions}} \\\\",
  bsl_rows,
  "\\midrule",
  "\\multicolumn{9}{l}{\\textit{Weight conditions}} \\\\",
  w14_rows,
  "\\midrule",
  "\\multicolumn{9}{l}{\\textit{Attribute conditions: high out\\_degree (249)}} \\\\",
  w5_rows,
  "\\midrule",
  "\\multicolumn{9}{l}{\\textit{Attribute conditions: high $\\alpha$ (0.95)}} \\\\",
  w6_rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(latex, file.path(out_dir, "ofat_indegree_table.tex"))
cat("Saved ofat_indegree_table.csv and .tex to", out_dir, "\n")
