# Regenerated by Claude Code
# Dumbbell plot: planted-node in-degree, P5 (simultaneous) vs PS5 (staggered)
# Metrics computed on planted nodes (planted_nodes_line_number != -1),
# pooled across 3 replicates per condition.

rm(list = ls())
library(data.table)
library(ggplot2)
library(patchwork)

# ── Paths & thresholds ────────────────────────────────────────────────────────
root_dir <- "/projects/illinois/eng/cs/chackoge/illinoiscomputes/abm/v6/chacko/planted_exps"
out_dir  <- root_dir

BSL_THRESH_999  <- 1707   # baseline 99.9th percentile
BSL_THRESH_9999 <- 9018   # baseline 99.99th percentile

# ── Condition → directory stems ───────────────────────────────────────────────
cond_dirs <- c(
  "fit_dom_restr"       = "fit_dom_restr",
  "fit_dom_unrestr"     = "fit_dom_unrestr",
  "historical_reference"= "historical_reference",
  "soc_dom_restr"       = "soc_dom_restr",
  "soc_dom_unrestr"     = "soc_dom_unrestr"
)

cond_labels <- c(
  "fit_dom_restr"        = "Fit-dom\nrestr.",
  "fit_dom_unrestr"      = "Fit-dom\nunrestr.",
  "historical_reference" = "Reference",
  "soc_dom_restr"        = "Soc-dom\nrestr.",
  "soc_dom_unrestr"      = "Soc-dom\nunrestr."
)

# ── Compute stats for one series (p5 or ps5) ──────────────────────────────────
compute_stats <- function(series) {
  series_dir <- file.path(root_dir, paste0(series, "_series"))

  rbindlist(lapply(names(cond_dirs), function(cond) {
    dirs <- paste0(series, cond_dirs[cond], "_r", 0:2)
    pool <- rbindlist(lapply(dirs, function(d) {
      f  <- file.path(series_dir, d, "output", "nodelist.csv")
      dt <- fread(f, select = c("planted_nodes_line_number", "in_degree"))
      dt[planted_nodes_line_number != -1, .(in_degree)]
    }))
    x <- pool$in_degree
    cat(sprintf("%-6s %-22s  n=%d  median=%g\n", series, cond, length(x), median(x)))
    data.table(
      series  = series,
      cond    = cond,
      median  = median(x),
      pct_999 = 100 * mean(x >= BSL_THRESH_999),
      pct_9999= 100 * mean(x >= BSL_THRESH_9999)
    )
  }))
}

cat("Computing P5...\n");  p5  <- compute_stats("p5")
cat("Computing PS5...\n"); ps5 <- compute_stats("ps5")

# ── Combine and factor-order conditions ───────────────────────────────────────
dt <- rbind(
  p5 [, series := "P5 (simultaneous)"],
  ps5[, series := "PS5 (staggered)"]
)

cond_order <- names(cond_labels)   # bottom → top in plot
dt[, cond_label := factor(cond_labels[cond], levels = rev(cond_labels[cond_order]))]
dt[, series     := factor(series, levels = c("P5 (simultaneous)", "PS5 (staggered)"))]

print(dt)

# ── Colours ───────────────────────────────────────────────────────────────────
COL_P5   <- "#2166ac"
COL_PS5  <- "#d6604d"
COL_LINE <- "#aaaaaa"
FONT     <- 16

palette  <- c("P5 (simultaneous)" = COL_P5, "PS5 (staggered)" = COL_PS5)

# ── Dumbbell helper ───────────────────────────────────────────────────────────
make_dumbbell <- function(dt_wide, x_col, xlabel, xlim = NULL, pct_line = FALSE) {
  seg <- dt_wide[, .(cond_label,
                     x_p5  = get(paste0(x_col, "_p5")),
                     x_ps5 = get(paste0(x_col, "_ps5")))]

  long <- rbind(
    dt_wide[, .(cond_label, x = get(paste0(x_col, "_p5")),  series = "P5 (simultaneous)")],
    dt_wide[, .(cond_label, x = get(paste0(x_col, "_ps5")), series = "PS5 (staggered)")]
  )
  long[, series := factor(series, levels = c("P5 (simultaneous)", "PS5 (staggered)"))]

  p <- ggplot() +
    geom_segment(data = seg,
                 aes(x = x_p5, xend = x_ps5, y = cond_label, yend = cond_label),
                 colour = COL_LINE, linewidth = 1.2) +
    geom_point(data = long,
               aes(x = x, y = cond_label, colour = series),
               size = 3.5) +
    scale_colour_manual(values = palette, name = NULL) +
    labs(x = xlabel, y = NULL) +
    theme_bw(base_size = FONT) +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.minor   = element_blank(),
      panel.grid.major.x = element_line(linetype = "dotted", linewidth = 0.7, colour = "grey70"),
      axis.text.y        = element_text(size = FONT - 1),
      axis.text.x        = element_text(size = FONT - 2),
      axis.title.x       = element_text(size = FONT),
      legend.position    = "none",
      panel.border       = element_rect(colour = "grey80")
    )

  if (!is.null(xlim)) p <- p + scale_x_continuous(limits = xlim)
  if (pct_line)       p <- p + geom_vline(xintercept = 100, linetype = "dashed",
                                           colour = "#cccccc", linewidth = 0.8)
  p
}

# ── Wide format for segment drawing ──────────────────────────────────────────
wide <- dcast(dt, cond + cond_label ~ series,
              value.var = c("median", "pct_999", "pct_9999"))
setnames(wide,
  c("median_P5 (simultaneous)", "median_PS5 (staggered)",
    "pct_999_P5 (simultaneous)", "pct_999_PS5 (staggered)",
    "pct_9999_P5 (simultaneous)", "pct_9999_PS5 (staggered)"),
  c("median_p5", "median_ps5", "pct_999_p5", "pct_999_ps5", "pct_9999_p5", "pct_9999_ps5")
)

# ── Build panels ──────────────────────────────────────────────────────────────
p1 <- make_dumbbell(wide, "median",   "Median in-degree") +
  scale_x_continuous(labels = function(x)
    ifelse(x >= 1000, paste0(x / 1000, "k"), as.character(x))) +
  theme(axis.text.y = element_text(size = FONT - 1))

p2 <- make_dumbbell(wide, "pct_999",  "% Agents >= p99.9 bsl",
                    xlim = c(25, 110), pct_line = TRUE) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  # add legend to panel 2 (lower left, matching original)
  guides(colour = guide_legend(override.aes = list(size = 4))) +
  theme(legend.position      = c(0.3, 0.15),
        legend.background    = element_blank(),
        legend.text          = element_text(size = FONT - 2))

p3 <- make_dumbbell(wide, "pct_9999", "% Agents >= p99.99 bsl",
                    xlim = c(25, 110), pct_line = TRUE) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

# ── Combine and save ──────────────────────────────────────────────────────────
combined <- p1 + p2 + p3 + plot_layout(widths = c(1.15, 1, 1))

ggsave(file.path(out_dir, "p5_ps5_comparison.pdf"), combined,
       width = 15, height = 5.5, units = "in", dpi = 300)
ggsave(file.path(out_dir, "p5_ps5_comparison.png"), combined,
       width = 15, height = 5.5, units = "in", dpi = 300)
ggsave(file.path(out_dir, "p5_ps5_comparison.eps"), combined,
       width = 15, height = 5.5, units = "in", dpi = 300, device = "eps")

cat("Saved p5_ps5_comparison.pdf/.png/.eps to", out_dir, "\n")
