# Regenerated by Claude Code. Reviewed and edited by George Chacko
# Table: planted node experiment results, P5 vs PS5 across 5 conditions
# Rank 1 = planted node achieves max in_degree among all agent-type nodes

rm(list = ls())
library(data.table)

# ── Paths & thresholds ────────────────────────────────────────────────────────
root_dir <- "/projects/illinois/eng/cs/chackoge/illinoiscomputes/abm/v6/chacko/planted_exps"
out_dir  <- root_dir

BSL_THRESH_999  <- 1707
BSL_THRESH_9999 <- 9018

# ── Condition mapping ─────────────────────────────────────────────────────────
cond_dirs <- c(
  "Fit-dom restr."   = "fit_dom_restr",
  "Fit-dom unrestr." = "fit_dom_unrestr",
  "Reference"        = "historical_reference",
  "Soc-dom restr."   = "soc_dom_restr",
  "Soc-dom unrestr." = "soc_dom_unrestr"
)

# ── Compute stats for one series ──────────────────────────────────────────────
compute_stats <- function(series) {
  series_dir <- file.path(root_dir, paste0(series, "_series"))

  rbindlist(lapply(names(cond_dirs), function(label) {
    stem <- cond_dirs[label]
    dirs <- paste0(series, stem, "_r", 0:2)

    # Pool planted nodes across replicates for median and % stats
    pool <- rbindlist(lapply(dirs, function(d) {
      f  <- file.path(series_dir, d, "output", "nodelist.csv")
      dt <- fread(f, select = c("type", "planted_nodes_line_number", "in_degree"))
      dt[planted_nodes_line_number != -1, .(in_degree)]
    }))

    # Rank-1: per replicate, does best planted node == max agent in_degree?
    rank1 <- sum(sapply(dirs, function(d) {
      f  <- file.path(series_dir, d, "output", "nodelist.csv")
      dt <- fread(f, select = c("type", "planted_nodes_line_number", "in_degree"))
      max_planted <- max(dt[planted_nodes_line_number != -1, in_degree])
      max_agent   <- max(dt[type == "agent", in_degree])
      max_planted == max_agent
    }))

    x <- pool$in_degree
    data.table(
      series   = series,
      cond     = label,
      median   = median(x),
      top_01   = round(100 * mean(x >= BSL_THRESH_999)),
      top_001  = round(100 * mean(x >= BSL_THRESH_9999)),
      rank1    = rank1
    )
  }))
}

cat("Computing P5...\n");  p5  <- compute_stats("p5")
cat("Computing PS5...\n"); ps5 <- compute_stats("ps5")

print(p5); print(ps5)

# ── Format display columns ────────────────────────────────────────────────────
fmt <- function(dt) {
  dt[, .(
    cond,
    median  = formatC(round(median),  format = "d", big.mark = ","),
    top_01  = paste0(top_01,  "\\%"),
    top_001 = paste0(top_001, "\\%"),
    rank1   = as.character(rank1)
  )]
}

p5f  <- fmt(p5)
ps5f <- fmt(ps5)

# ── Build LaTeX ───────────────────────────────────────────────────────────────
rows <- sapply(seq_len(nrow(p5f)), function(i) {
  paste0(
    sprintf("%-20s", p5f$cond[i]), " & ",
    p5f$median[i],  " & ", p5f$top_01[i],  " & ",
    p5f$top_001[i], " & ", p5f$rank1[i],   " & ",
    ps5f$median[i], " & ", ps5f$top_01[i], " & ",
    ps5f$top_001[i]," & ", ps5f$rank1[i],
    " \\\\"
  )
})

latex <- c(
  "\\begin{table}[ht]",
  "\\centering",
  "\\caption{Planted node experiment results for simultaneous (P5) and staggered (PS5)",
  "entry strategies across five conditions (5 planted nodes per condition per",
  "replicate, 3 replicates per condition, 15 planted nodes per condition total).",
  "Median in-degree, percentage of planted nodes exceeding the baseline top 0.1\\%",
  "threshold ($\\geq 1,707$ citations) and top 0.01\\% threshold ($\\geq 9,018$",
  "citations), and number of rank-1 finishes (across 15 nodes $\\times$ 3",
  "replicates) are reported for each strategy. P5 nodes are planted simultaneously in year 1 and PS5 nodes are planted in",
  "staggered fashion, years 1--5. Values are pooled across 3 replicates.",
  "\\textit{Provenance note:} P5 percentage values are computed from the March 4, 2025",
  "run in \\texttt{planted\\_exps/p5\\_series}, generated by Claude Code. An earlier",
  "Claude Code run (March 1, 2025, \\texttt{claude\\_p5\\_ps5/}) covers the Reference",
  "condition only. The P5 series appears to have been regenerated between these dates",
  "without a record of the change, causing the percentage values to differ from",
  "previously reported results.}",
  "\\label{tab:p5_ps5_combined}",
  "\\setlength{\\tabcolsep}{4pt}",
  "\\begin{tabular}{lrrrr rrrr}",
  "\\toprule",
  "& \\multicolumn{4}{c}{P5 (simultaneous)} & \\multicolumn{4}{c}{PS5 (staggered)} \\\\",
  "\\cmidrule(lr){2-5} \\cmidrule(lr){6-9}",
  "Condition & Median & Top 0.1\\% & Top 0.01\\% & Rank 1 & Median & Top 0.1\\% & Top 0.01\\% & Rank 1 \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(latex, file.path(out_dir, "p5_ps5_table.tex"))
write.csv(rbind(p5[, series := "P5"], ps5[, series := "PS5"]),
          file.path(out_dir, "p5_ps5_table.csv"), row.names = FALSE)

cat("Saved p5_ps5_table.tex and .csv to", out_dir, "\n")
